### ISSUE TITLE
Disable spammy log message

### ISSUE THREAD

**Issue by eugenesvk** [jfcherng/Sublime-AutoSetSyntax#14]
I've set `enable_log` to `false`, yet still get `[AutoSetSyntax] ⏳ Calm down! View has gone or the plugin is not ready yet.`

Not sure why I should be worried, but if I were, the message wouldn't calm me down :), it doesn't imply I need to do anything

Could you please disable this message as well?

**Comment by jfcherng** [comment]
Sure, that one is more of a debug msg. Done in 8256b2b. Released in `4114-2.10.4` and should be available within hours.
