### ISSUE TITLE
plugin doesnt respect debug option

### ISSUE THREAD

**Issue by ctf0** [jfcherng/Sublime-AutoSetSyntax#2]
``` json
"log_level": "NOTSET",
```

but still get details in console :(.

```
AutoSetSyntax: [INFO] match syntax file "PHP/PHP" with "Packages/PHP/PHP Source.sublime-syntax"
INFO:AutoSetSyntax:match syntax file "PHP/PHP" with "Packages/PHP/PHP Source.sublime-syntax"
```

**Comment by jfcherng** [comment]
I actually could not reproduce this, but I found that "NOTSET" is just not what I thought in the logging module. So I add a new log_level "NOTHING" which is more clear and hopefully working as my expectation. You may try

```
"log_level": "NOTHING",
```

in the next release (1.8.5).

**Comment by ctf0** [comment]
all good now, thanx
