### ISSUE TITLE
php binding

### ISSUE THREAD

**Issue by ctf0** [jfcherng/Sublime-AutoSetSyntax#4]
because ST now ships with 2 syntax `php source & php` so the plugin will always go for the first which is `php source` can we change that to only go with the `php` ?

**Comment by jfcherng** [comment]
Just tried a clean ST 3114 with default plugin settings and didn't have this issue. What's your plugin settings?

**Comment by ctf0** [comment]
ST 3120

``` json
{
    "log_level": "NOTHING",
    "syntax_mapping": {
        "Laravel Blade": [
            "blade"
        ],
        "HTML/HTML": [
            "html",
            "doct",
            "<"
        ],
        "JavaScript/JavaScript": [
            "js"
        ],
        "PHP/PHP": [
            "php",
        ],
        "CSS/CSS": [
            "css"
        ],
        "SASS": [
            "sass"
        ]
    }
}
```

**Comment by jfcherng** [comment]
You may use

``` javascript
        "PHP/PHP.": [
            "php",
        ],
```

`PHP/PHP.` matches `PHP/PHP.sublime-syntax` but not `PHP Source.sublime-syntax`.

## 

Thanks. Readme has been updated.

**Comment by ctf0** [comment]
many thanx, maybe u can keep it as `PHP/PHP` for normal and `PHP/PHP Source` for the other one ?

**Comment by jfcherng** [comment]
Nope. I don't want to modify codes for such an exception and this exception can be easily resolved.
What's more, the meaning of a key in the setting is actually `the partial path of a syntax file` but not `syntax/syntax`.

**Comment by ctf0** [comment]
aha , okay, thanx again
