### ISSUE TITLE
[Bug] Not colored git log

### ISSUE THREAD

**Issue by Kristinita** [jfcherng/Sublime-AutoSetSyntax#5]
### Summary

Not colored git log.
### Expected behavior

![Right git log](https://packagecontrol.io/readmes/img/33593c0f5b36156563e846531b7f94410fe427cb.gif)
### Actual behavior

![My git log](http://i.imgur.com/Fz0SMn2.png)
### Steps to reproduce

I install SublimeANSI and SideBarGit → I insert to command prompt command `git config --global alias.l "log --graph --date=short --pretty=format:'%C(yellow bold)%h%Creset%C(auto)%d%Creset - %s %C(green bold)[%an]%Creset %C(blue bold)(%ad, %cr)%Creset'"` → my `User\AutoSetSyntax.sublime-settings` file:

``` json
{
    "syntax_mapping":
    {
        "ANSIescape/ANSI.tmLanguage":
        [
            "^\\s*\\[SideBarGit@.*\\] git l\\b"
        ]
    },
    "working_scope": "(?x)^(text.plain | source.diff)\\\\b"
}
```

I click right mouse button on any file of my local git repository → Git → Liberal Git Command → `git l`.
### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by jfcherng** [comment]
Does the git log get colored if you set the syntax to `ANSI` manually?

And

```
    "working_scope": "(?x)^(text.plain | source.diff)\\\\b"
                                                     ^^^^ just use "\\"
```

**Comment by Kristinita** [comment]
I'm sorry, the [**Preferences Editor bug**](https://bitbucket.org/klorenz/sublimepreferenceseditor/issues/9/bug-adding-exrta-slashes). Now colored git log works for me.

If you add more video examples, how use AutoSetSyntax, users of your plugin to be fine 😸 .
