### ISSUE TITLE
Interference with SublimeTabr package

### ISSUE THREAD

**Issue by usernamelectro** [jfcherng/Sublime-AutoSetSyntax#9]
**Description of the bug**

Cannot use [SublimeTabr](https://github.com/mghweb/SublimeTabr) with AutSetSyntax, unless logging is disabled in AutoSetSyntax.sublime-settings file.

**Steps to reproduce**

**0.** Start Sublime Text in Safe Mode

**1.** Install Package Control

**2.** Install "AutoSetSyntax" package

**3.** Install "tabr" package

**4.** Enable sublime.log_commands(True) in the Console

**5.** Add several rows like these:

```
    I =
    coffee =
    milk =
    please =
    water =
    bread =
```

**5.** Try to create tab order by finding all occurrences of the '=' sign and then make multiple cursor selection. Then try to create tab order and press Ctrl+Shift+Alt+T (default tabr keybinding)

**6.** Type something then press tab to jump to another placeholder, cursor goes to the end of the file instead of going to every tab stop that was created by tabr.

**7.** After the tabr command the Console is filled with this line:

    command: tabr
    command: auto_set_syntax_append_log {"msg": "[AutoSetSyntax] ❌ Cannot help View(50, \"C:/Users/Username/Creative/German/English practice.txt\") because {'event': \"<ListenerEvent.MODIFY('modify')>\", 'reason': 'no matching rule'}"}

**8.** tabr package works fine after disabling logging in AutoSetSyntax.sublime-settings file

  ```
    {
         "enable_log": false,
    }
  ```

**Actual behavior**

https://user-images.githubusercontent.com/8273701/153392964-4b9a3978-17ea-4973-ad47-5cf650886848.mp4

**Expected behavior**

https://user-images.githubusercontent.com/8273701/153392992-54a8c3eb-4bc0-43ad-912c-5693ca3d72ac.mp4

Build: 4126
OS: Windows 10 21H2

**Comment by jfcherng** [comment]
The root cause is not from here but back to when SublimeTabr is invented, there is probably no concept of plugin's custom output panel. In SublimeTabr 's [`on_modified` listener](https://github.com/mghweb/SublimeTabr/blob/43b0afdecb274a748c9ebfa4fe8e56127b0f6540/tabr.py#L95) just count all views in, including AutoSetSyntax's output (log) panel. A possible fix can be the following but the author maybe no longer maintain the plugin now. 

```diff
 class TabrCountCommand(sublime_plugin.EventListener):
     def on_modified(self, view):
 
         global TabrVariables
         
+        if (view != sublime.active_window().active_view()):
+            return
+
         if (len(TabrVariables['TabrSelections']) > 0): 
```

SublimeTabr should associate TabrVariables with view's ID , otherwise when user change to another file, tab order is messed up, but anyway 🤷

**Comment by jfcherng** [comment]
I do find something can be improved in AutoSetSyntax's side, thanks for reporting this :)
But unfortunately, this has to be solve on SublimeTabr's side.

**Comment by usernamelectro** [comment]
> The root cause is not from here but back to when SublimeTabr is invented, there is probably no concept of plugin's custom output panel. In SublimeTabr 's [`on_modified` listener](https://github.com/mghweb/SublimeTabr/blob/43b0afdecb274a748c9ebfa4fe8e56127b0f6540/tabr.py#L95) just count all views in, including AutoSetSyntax's output (log) panel. A possible fix can be the following but the author maybe no longer maintain the plugin now.
> 
> ```diff
>  class TabrCountCommand(sublime_plugin.EventListener):
>      def on_modified(self, view):
>  
>          global TabrVariables
>          
> +        if (view != sublime.active_window().active_view()):
> +            return
> +
>          if (len(TabrVariables['TabrSelections']) > 0): 
> ```
> 
> SublimeTabr should associate TabrVariables with view's ID , otherwise when user change to another file, tab order is messed up, but anyway 🤷

Thanks for the quality explanation. I hope someone has the time to maintain the SublimeTabr, because it is so useful - it is almost like it needs to be the default package of Sublime Text. Imagine having multiple placeholders that you can storm through with just typing a tab away.

**Comment by jfcherng** [comment]
If you think the plugin author is probably no longer interesting in fixing this, you can fix it locally via overwrite plugin file(s).
